### ISSUE TITLE
Request to make ReadoutIssues.hpp visible from other packages

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/readout#101]
I already mentioned this to Florian earlier today, and I wanted to file an Issue for completeness...

I'm currently using the readout::BufferedFileWriter in the TPSetWriter module that I'm developing in the _dfmodules_ repo, and I noticed that when I include readout/BufferedFileWriter.hpp, I get a complaint that ReadoutIssues.hpp is not found.

I see that ReadoutIssues.hpp is currently in readout/src, and I suspect that it needs to be moved to readout/include/readout for it to be visible to packages other than _readout_.

Florian mentioned that he would look into changing this.  Thanks in advance for this help,
Kurt

**Comment by roland-sipos** [comment]
Hi Kurt,

Florian did move it in: https://github.com/DUNE-DAQ/readout/pull/102

Cheers
