### ISSUE TITLE
Need to multiply hit time-over-threshold by `clocksPerTPCTick`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/readout#116]
In this line:

https://github.com/DUNE-DAQ/readout/blob/c5a150b3c5dcc825873c2c0755184e7ad6b36f80/src/wib/WIBFrameProcessor.hpp#L399

The TriggerPrimitive time_over_threshold should be in timing-system ticks, but `hit_tover` is in TPC ticks, so there needs to be a multiply by `clocksPerTPCTick`.

**Comment by roland-sipos** [comment]
multiply added in bf9fed9
