### ISSUE TITLE
undefined symbol *PdspChannelMapService*

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/readout#128]
With the latest code on the develop branch of the readout repo (used from the N21-09-28 nightly build), I'm seeing errors when trying to run the system with --enable-software-tpg.

The error (at runtime) is the following:

- `daq_application: symbol lookup error: /home/biery/dunedaq/28Sep/install/readout/lib64/libreadout_DataLinkHandler_duneDAQModule.so: undefined symbol: _ZN5swtpg21PdspChannelMapServiceC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_`

I see that the PdspChannelMapService moved from one directory to another in a recent commit.  Maybe that is related?
In any case, it would be great if someone could look into this.
Thanks,
Kurt

**Comment by roland-sipos** [comment]
Thanks Kurt for catching this.
Fixed in: 1550c51
