### ISSUE TITLE
Need index check in `AccessableProducerConsumerQueue`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/readout#17]
If `index > size_`, this line will read past the end of the array:
https://github.com/DUNE-DAQ/readout/blob/ab8630e6839218b474ea588c1e6c8e43a7247a88/src/AccessableProducerConsumerQueue.hpp#L143

**Comment by roland-sipos** [comment]
Hence I added the following line:
https://github.com/DUNE-DAQ/readout/blob/ab8630e6839218b474ea588c1e6c8e43a7247a88/src/AccessableProducerConsumerQueue.hpp#L140

Isn't that sufficient? Please let me know. Did you reproduce a trigger where it went over to an invalid index?

**Comment by philiprodrigues** [comment]
Sorry, I got the condition wrong. It should be: if `index>2*size_`, then at line 143, `recordIdx == currentRead + index - size_ > currentRead + size_ > size_`. I didn't actually have this occur anywhere in the code, I just noticed it while trying to track down something else.

**Comment by roland-sipos** [comment]
After a discussion with Phil, I understood the issue better.
Fixed in 9fc55b4
