### ISSUE TITLE
FakeCardReader crashes at start if the input file is missing

### ISSUE THREAD

**Issue by alessandrothea** [DUNE-DAQ/readout#23]
The existence of the input file is checked in `do_conf` and an `ers::Error` is thrown.
Alas there is no protection against very smart users (me!) that miss the ERROR message and hit start.
It may make sense to add an extra check in `do_start` that prevents the application to crash.

Alessandro

**Comment by roland-sipos** [comment]
Absolutely agreed. In run, we need to ensure that the conditions are fine. (And an unponed file and empty buffer is clearly not a fine condition.)

**Comment by ShyamB97** [comment]
I have added a check in do_start which checks the number of elements in source_buffer_, and if the number is zero an error is thrown. This prevents the crash and prints an error message looking like this:
`2021-Feb-01 12:13:10,863 ERROR [dunedaq::readout::FakeCardReader::do_start(...) at /users/sb16165/minidaqapp/readout/sourcecode/readout/plugins/FakeCardReader.cpp:88]  Readout Configuration Error: Source buffer is empty, check configuration for errors!
`
Should I leave the error type as a configuration error or as something else?

**Comment by glehmannmiotto** [comment]
Can the origin of the problem be included in the error? No file exists, no permissions to read, …

**Comment by ShyamB97** [comment]
Something like this?

"Source buffer is empty, binary file was not read during the configuration."

**Comment by glehmannmiotto** [comment]
But then the error shall be thrown in first place during configure, no?

**Comment by ShyamB97** [comment]
It already is. In that case it might be better to print this as a warning rather than an error?

**Comment by alessandrothea** [comment]
No, this is definitely an error. The module is unusable if the input file is not available.
I agree with @glehmannmiotto that the message is too generic and it should be more specific
on the cause of the failure to open the file.
