### ISSUE TITLE
FakeTPReader

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/readout#25]
We need a module that is capable of reading TPs from a file and replay it.

Either we modify the FakeCardReader to be able to enable links with different FE type (TP) or we make a new module.

**Comment by roland-sipos** [comment]
FakeCardReader to add 6th link which will deliver TPs from a file. 
https://github.com/DUNE-DAQ/readout/blob/develop/plugins/FakeCardReader.hpp

**Comment by hristovaivana** [comment]
A status update summary for discussion (link to slides)
https://docs.google.com/presentation/d/1C-mDEATaNSk__mhFme6C-rsufvQJ_rfIc7aI2vlV3g8/edit#slide=id.ga1dcc77bb9_0_194
