### ISSUE TITLE
Multi-link FakeCardReader breaks fake timestamp creation.

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/readout#3]
The fresh addition of multi-link support to the FakeCardReader module breaks the offset calculation of timestamp and frames. To be fixed ASAP.

Last stable commit hash: 95080fc6f0c15bd4b93be963b6f4774502ff51ea

**Comment by glehmannmiotto** [comment]
fixed in master. With high rates nevertheless there are TS mismatches, I suppose that the app cannot keep up.

**Comment by roland-sipos** [comment]
tested, thanks for the fix
