### ISSUE TITLE
Stats should be initialized before use

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/readout#4]
`ReadoutModel`'s `packet_count_` and `request_count_` members can be accessed uninitialized in `run_stats()`. Probably easiest to just initialize them to zero here:

https://github.com/DUNE-DAQ/readout/blob/b320cc916f53fe92bf439d833ed7a7dc1c8300f5/src/ReadoutModel.hpp#L246

**Comment by roland-sipos** [comment]
Thanks, fixed in e60287b
