### ISSUE TITLE
RawWIBTp linter

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/readout#42]
There are a lot of problems reported by the linter for the RawWIBTp:

> =========================Checking sourcecode/readout/include/readout/RawWIBTp.hpp=========================
sourcecode/readout/include/readout/RawWIBTp.hpp:8:  #ifndef header guard has wrong style, please use: READOUT_INCLUDE_READOUT_RAWWIBTP_HPP_  [build/header_guard] [5]
sourcecode/readout/include/readout/RawWIBTp.hpp:235:  #endif line should be "#endif  // READOUT_INCLUDE_READOUT_RAWWIBTP_HPP_"  [build/header_guard] [5]
sourcecode/readout/include/readout/RawWIBTp.hpp:18:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:29:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:31:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:35:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:44:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:52:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:53:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:59:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:79:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:88:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:89:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:108:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:114:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:115:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:158:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:183:  Access specifier "public" has already appeared in class RawWIBTp  [readability/access_specifiers] [5]
sourcecode/readout/include/readout/RawWIBTp.hpp:185:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:186:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:187:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:188:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:189:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:191:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:192:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:193:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:194:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:195:  An unsigned integer appears to be used here.  [build/unsigned] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:216:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
sourcecode/readout/include/readout/RawWIBTp.hpp:224:  "cout" should not be used for output in DUNE DAQ software.  [runtime/output_format] [3]
Done processing sourcecode/readout/include/readout/RawWIBTp.hpp
Total errors found: 30

**Comment by roland-sipos** [comment]
Hi @hristovaivana ! Do you have any news on this?

**Comment by hristovaivana** [comment]
Hi Roland,

I am working on this and I hope to be finished by this evening. As soon as I am ready I will
update my branch and the github issue, so hopefully we can merge the changes to 'develop'
soon. Sorry for the late reply.

Thanks,
Ivana
________________________________
