### ISSUE TITLE
Disable stats threads

### ISSUE THREAD

**Issue by glehmannmiotto** [DUNE-DAQ/readout#49]
Now that opmon is available it would be preferable to disable the statistics threads. You can publish rates in get_info, if you like.

**Comment by roland-sipos** [comment]
For calculating the rate we need to know the time delta between two get_info calls. Can opmon expose the configured poll intervals? (  If so, I can remove the stats_thread. But otherwise I need it to know `elapsed_seconds` )

**Comment by roland-sipos** [comment]
@floriangroetschla is expanding opmon varioables in the package.
