### ISSUE TITLE
Fragment sizes don't seem to be as consistent with latest code, compared to v2.6 code

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/readout#93]
I mentioned this on the MiniDAQ Dev call today, but I wanted to be more concrete than just a comment in a meeting, so I'm creating this Issue.

I noticed that the Fragment sizes in the HDF5 data files that we are writing in our test systems today are not as consistent as they were with the v2.6.0 code.

With the v2.6.0 code and the default mdapp_multiru_gen.py options, except for -s 10, we would consistently see a Fragment size of 22352.

With the latest code on the HEAD of the develop branch of the _readout_ package and many other packages, we see Fragment sizes of 22352 and 27920.  The two Fragments in the TriggerRecord always seem to have the same size, so whatever is happening seems to be somewhat global.

I just ran a couple of tests in which I looked at the TriggerDecision request window, and that seems consistently set to 1000 in both my 2.6 and 'head of develop' software areas.  So, I suspect that the change between v2.6 and now is not because something in the _trigger_ package has changed.

**Comment by roland-sipos** [comment]
Related to Issue #15
