### ISSUE TITLE
Multiple runs in the same DAQ session fail during the second run

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/readout#96]
Several notes on this:

1) The error that is printed out by _nanorc_ is the following:

```
ERROR    Timeout while waiting for a reply from ruemu0 for command stop
```

2) To reproduce the issue, you can create a new software area using [these instructions](https://github.com/DUNE-DAQ/minidaqapp/wiki/Instructions-for-setting-up-a-v2.8.0-development-environment) (including the download of `frames.bin`), then run the following commands:

```
python -m minidaqapp.nanorc.mdapp_multiru_gen --host-ru localhost -d ./frames.bin -o . -s 10 mdapp_4proc
nanorc mdapp_4proc boot init conf start 101 wait 2 resume wait 10 pause wait 2 stop start 102 wait 2 resume wait 10 pause wait 2 stop scrap terminate
```

This sequence of commands should produce two raw data files, but only the first run produces a data file.

3) I've run tests with various versions of the software, and my sense is that this problem is related to changes in the _readout_ repo.  (At first, I thought that the problem was somewhere else).  For reference, with tagged v2.6.0 code, I **do not** see the problem.  With the latest _readout, dataformats, and dfmessages_ code and everything else using the v2.6 tag, I **do** see the problem, so that is why I think that it something to do with _readout_.

**Comment by floriangroetschla** [comment]
Resolved by cf1032f
